import pandas as pd
from datetime import datetime

# Load the existing data
data_path = r'C:\Users\hp\Desktop\week 11\data\raw\ethiopia_fi_unified_data.xlsx'
data_df = pd.read_excel(data_path, sheet_name='ethiopia_fi_unified_data')
impact_links_df = pd.read_excel(data_path, sheet_name='Impact_sheet')

# Get the next record IDs
last_data_id = int(data_df['record_id'].str.extract(r'(\d+)')[0].max())
last_impact_id = int(impact_links_df['record_id'].str.extract(r'(\d+)')[0].max())

print(f"Last data record ID: REC_{last_data_id:04d}")
print(f"Last impact link ID: IMP_{last_impact_id:04d}")

# Additional observations to add
new_observations = [
    {
        'record_id': f'REC_{last_data_id + 1:04d}',
        'record_type': 'observation',
        'category': None,
        'pillar': 'ACCESS',
        'indicator': 'Smartphone Penetration Rate',
        'indicator_code': 'ACC_SMARTPHONE',
        'indicator_direction': 'higher_better',
        'value_numeric': 35.0,
        'value_text': None,
        'value_type': 'percentage',
        'unit': '%',
        'observation_date': '2023-12-31',
        'period_start': None,
        'period_end': None,
        'fiscal_year': '2023',
        'gender': 'all',
        'location': 'national',
        'region': None,
        'source_name': 'GSMA Mobile Economy Ethiopia',
        'source_type': 'research',
        'source_url': 'https://www.gsma.com/mobileeconomy/ethiopia/',
        'confidence': 'medium',
        'related_indicator': None,
        'relationship_type': None,
        'impact_direction': None,
        'impact_magnitude': None,
        'impact_estimate': None,
        'lag_months': None,
        'evidence_basis': None,
        'comparable_country': None,
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': 'Smartphone penetration reached 35% in 2023',
        'notes': 'Enabler for digital payment adoption'
    },
    {
        'record_id': f'REC_{last_data_id + 2:04d}',
        'record_type': 'observation',
        'category': None,
        'pillar': 'ACCESS',
        'indicator': 'ATM Density per 100,000 adults',
        'indicator_code': 'ACC_ATM_DENSITY',
        'indicator_direction': 'higher_better',
        'value_numeric': 12.5,
        'value_text': None,
        'value_type': 'rate',
        'unit': 'per 100k',
        'observation_date': '2023-12-31',
        'period_start': None,
        'period_end': None,
        'fiscal_year': '2023',
        'gender': 'all',
        'location': 'national',
        'region': None,
        'source_name': 'NBE Annual Report',
        'source_type': 'regulator',
        'source_url': 'https://nbe.gov.et/',
        'confidence': 'medium',
        'related_indicator': None,
        'relationship_type': None,
        'impact_direction': None,
        'impact_magnitude': None,
        'impact_estimate': None,
        'lag_months': None,
        'evidence_basis': None,
        'comparable_country': None,
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': 'ATM density of 12.5 per 100,000 adults',
        'notes': 'Physical access to financial services'
    },
    {
        'record_id': f'REC_{last_data_id + 3:04d}',
        'record_type': 'observation',
        'category': None,
        'pillar': 'ACCESS',
        'indicator': 'Bank Branches per 100,000 adults',
        'indicator_code': 'ACC_BRANCH_DENSITY',
        'indicator_direction': 'higher_better',
        'value_numeric': 8.3,
        'value_text': None,
        'value_type': 'rate',
        'unit': 'per 100k',
        'observation_date': '2023-12-31',
        'period_start': None,
        'period_end': None,
        'fiscal_year': '2023',
        'gender': 'all',
        'location': 'national',
        'region': None,
        'source_name': 'NBE Annual Report',
        'source_type': 'regulator',
        'source_url': 'https://nbe.gov.et/',
        'confidence': 'medium',
        'related_indicator': None,
        'relationship_type': None,
        'impact_direction': None,
        'impact_magnitude': None,
        'impact_estimate': None,
        'lag_months': None,
        'evidence_basis': None,
        'comparable_country': None,
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': 'Bank branch density of 8.3 per 100,000 adults',
        'notes': 'Physical access to banking services'
    },
    {
        'record_id': f'REC_{last_data_id + 4:04d}',
        'record_type': 'observation',
        'category': None,
        'pillar': 'ACCESS',
        'indicator': 'Mobile Money Agent Density',
        'indicator_code': 'ACC_AGENT_DENSITY',
        'indicator_direction': 'higher_better',
        'value_numeric': 45.2,
        'value_text': None,
        'value_type': 'rate',
        'unit': 'per 100k',
        'observation_date': '2024-06-30',
        'period_start': None,
        'period_end': None,
        'fiscal_year': '2024',
        'gender': 'all',
        'location': 'national',
        'region': None,
        'source_name': 'GSMA Mobile Money Database',
        'source_type': 'research',
        'source_url': 'https://www.gsma.com/mobilemoney/',
        'confidence': 'medium',
        'related_indicator': None,
        'relationship_type': None,
        'impact_direction': None,
        'impact_magnitude': None,
        'impact_estimate': None,
        'lag_months': None,
        'evidence_basis': None,
        'comparable_country': None,
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': 'Mobile money agent density of 45.2 per 100,000 adults',
        'notes': 'Critical for cash-in/cash-out services'
    },
    {
        'record_id': f'REC_{last_data_id + 5:04d}',
        'record_type': 'observation',
        'category': None,
        'pillar': 'USAGE',
        'indicator': 'Digital Payment Adoption Rate',
        'indicator_code': 'USG_DIGITAL_PAYMENT',
        'indicator_direction': 'higher_better',
        'value_numeric': 35.0,
        'value_text': None,
        'value_type': 'percentage',
        'unit': '%',
        'observation_date': '2024-11-29',
        'period_start': '2024-10-15',
        'period_end': '2024-11-29',
        'fiscal_year': '2024',
        'gender': 'all',
        'location': 'national',
        'region': None,
        'source_name': 'Global Findex 2024',
        'source_type': 'survey',
        'source_url': 'https://www.worldbank.org/en/publication/globa...',
        'confidence': 'high',
        'related_indicator': None,
        'relationship_type': None,
        'impact_direction': None,
        'impact_magnitude': None,
        'impact_estimate': None,
        'lag_months': None,
        'evidence_basis': None,
        'comparable_country': None,
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': '35% of adults made or received digital payments',
        'notes': 'Key usage indicator for forecasting'
    },
    {
        'record_id': f'REC_{last_data_id + 6:04d}',
        'record_type': 'observation',
        'category': None,
        'pillar': 'ACCESS',
        'indicator': 'Account Ownership Rate',
        'indicator_code': 'ACC_OWNERSHIP',
        'indicator_direction': 'higher_better',
        'value_numeric': 14.0,
        'value_text': None,
        'value_type': 'percentage',
        'unit': '%',
        'observation_date': '2011-12-31',
        'period_start': None,
        'period_end': None,
        'fiscal_year': '2011',
        'gender': 'all',
        'location': 'national',
        'region': None,
        'source_name': 'Global Findex 2011',
        'source_type': 'survey',
        'source_url': 'https://www.worldbank.org/en/publication/globa...',
        'confidence': 'high',
        'related_indicator': None,
        'relationship_type': None,
        'impact_direction': None,
        'impact_magnitude': None,
        'impact_estimate': None,
        'lag_months': None,
        'evidence_basis': None,
        'comparable_country': None,
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': 'Account ownership was 14% in 2011',
        'notes': 'Baseline year for trend analysis'
    }
]

# Additional events to add
new_events = [
    {
        'record_id': f'EVT_{last_data_id + 1:04d}',
        'record_type': 'event',
        'category': 'regulation',
        'pillar': None,  # Events should NOT have pillar assignments
        'indicator': 'NBE Mobile Money Regulatory Framework',
        'indicator_code': 'EVT_NBE_MM_REG',
        'indicator_direction': None,
        'value_numeric': None,
        'value_text': None,
        'value_type': None,
        'unit': None,
        'observation_date': '2020-03-15',
        'period_start': None,
        'period_end': None,
        'fiscal_year': None,
        'gender': None,
        'location': 'national',
        'region': None,
        'source_name': 'National Bank of Ethiopia',
        'source_type': 'regulator',
        'source_url': 'https://nbe.gov.et/',
        'confidence': 'high',
        'related_indicator': None,
        'relationship_type': None,
        'impact_direction': None,
        'impact_magnitude': None,
        'impact_estimate': None,
        'lag_months': None,
        'evidence_basis': None,
        'comparable_country': None,
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': 'NBE issued mobile money regulatory framework enabling Telebirr launch',
        'notes': 'Critical regulatory enabler for mobile money'
    },
    {
        'record_id': f'EVT_{last_data_id + 2:04d}',
        'record_type': 'event',
        'category': 'infrastructure',
        'pillar': None,
        'indicator': 'Ethio Telecom 4G Network Expansion Phase 1',
        'indicator_code': 'EVT_4G_EXPANSION',
        'indicator_direction': None,
        'value_numeric': None,
        'value_text': None,
        'value_type': None,
        'unit': None,
        'observation_date': '2023-01-15',
        'period_start': None,
        'period_end': None,
        'fiscal_year': None,
        'gender': None,
        'location': 'national',
        'region': None,
        'source_name': 'Ethio Telecom',
        'source_type': 'operator',
        'source_url': 'https://www.ethiotelecom.et/',
        'confidence': 'high',
        'related_indicator': None,
        'relationship_type': None,
        'impact_direction': None,
        'impact_magnitude': None,
        'impact_estimate': None,
        'lag_months': None,
        'evidence_basis': None,
        'comparable_country': None,
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': 'Major 4G network expansion covering Addis Ababa and major cities',
        'notes': 'Infrastructure improvement supporting digital services'
    }
]

# Additional impact links to add
new_impact_links = [
    {
        'record_id': f'IMP_{last_impact_id + 1:04d}',
        'parent_id': f'EVT_{last_data_id + 1:04d}',  # Links to NBE MM Regulation
        'record_type': 'impact_link',
        'category': None,
        'pillar': 'ACCESS',
        'indicator': 'NBE MM Regulation effect on Mobile Money Accounts',
        'indicator_code': None,
        'indicator_direction': None,
        'value_numeric': 10.0,
        'value_text': None,
        'value_type': 'percentage',
        'unit': '%',
        'observation_date': '2020-03-15',
        'period_start': None,
        'period_end': None,
        'fiscal_year': None,
        'gender': 'all',
        'location': 'national',
        'region': None,
        'source_name': None,
        'source_type': None,
        'source_url': None,
        'confidence': 'medium',
        'related_indicator': 'ACC_MM_ACCOUNT',
        'relationship_type': 'enabling',
        'impact_direction': 'increase',
        'impact_magnitude': 'medium',
        'impact_estimate': 10.0,
        'lag_months': 15,
        'evidence_basis': 'theoretical',
        'comparable_country': 'Kenya',
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': None,
        'notes': 'Regulatory framework enabled Telebirr launch and subsequent growth'
    },
    {
        'record_id': f'IMP_{last_impact_id + 2:04d}',
        'parent_id': f'EVT_{last_data_id + 2:04d}',  # Links to 4G Expansion
        'record_type': 'impact_link',
        'category': None,
        'pillar': 'ACCESS',
        'indicator': '4G Expansion effect on Smartphone Penetration',
        'indicator_code': None,
        'indicator_direction': None,
        'value_numeric': 5.0,
        'value_text': None,
        'value_type': 'percentage',
        'unit': '%',
        'observation_date': '2023-01-15',
        'period_start': None,
        'period_end': None,
        'fiscal_year': None,
        'gender': 'all',
        'location': 'national',
        'region': None,
        'source_name': None,
        'source_type': None,
        'source_url': None,
        'confidence': 'medium',
        'related_indicator': 'ACC_SMARTPHONE',
        'relationship_type': 'enabling',
        'impact_direction': 'increase',
        'impact_magnitude': 'low',
        'impact_estimate': 5.0,
        'lag_months': 12,
        'evidence_basis': 'empirical',
        'comparable_country': None,
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': None,
        'notes': 'Better network coverage encourages smartphone adoption'
    },
    {
        'record_id': f'IMP_{last_impact_id + 3:04d}',
        'parent_id': f'EVT_{last_data_id + 2:04d}',  # Links to 4G Expansion
        'record_type': 'impact_link',
        'category': None,
        'pillar': 'USAGE',
        'indicator': '4G Expansion effect on Digital Payments',
        'indicator_code': None,
        'indicator_direction': None,
        'value_numeric': 8.0,
        'value_text': None,
        'value_type': 'percentage',
        'unit': '%',
        'observation_date': '2023-01-15',
        'period_start': None,
        'period_end': None,
        'fiscal_year': None,
        'gender': 'all',
        'location': 'national',
        'region': None,
        'source_name': None,
        'source_type': None,
        'source_url': None,
        'confidence': 'medium',
        'related_indicator': 'USG_DIGITAL_PAYMENT',
        'relationship_type': 'enabling',
        'impact_direction': 'increase',
        'impact_magnitude': 'low',
        'impact_estimate': 8.0,
        'lag_months': 6,
        'evidence_basis': 'empirical',
        'comparable_country': None,
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': None,
        'notes': 'Better connectivity enables more digital transactions'
    },
    {
        'record_id': f'IMP_{last_impact_id + 4:04d}',
        'parent_id': 'EVT_0001',  # Links to Telebirr Launch
        'record_type': 'impact_link',
        'category': None,
        'pillar': 'USAGE',
        'indicator': 'Telebirr effect on Digital Payment Adoption',
        'indicator_code': None,
        'indicator_direction': None,
        'value_numeric': 12.0,
        'value_text': None,
        'value_type': 'percentage',
        'unit': '%',
        'observation_date': '2021-05-17',
        'period_start': None,
        'period_end': None,
        'fiscal_year': None,
        'gender': 'all',
        'location': 'national',
        'region': None,
        'source_name': None,
        'source_type': None,
        'source_url': None,
        'confidence': 'medium',
        'related_indicator': 'USG_DIGITAL_PAYMENT',
        'relationship_type': 'direct',
        'impact_direction': 'increase',
        'impact_magnitude': 'medium',
        'impact_estimate': 12.0,
        'lag_months': 12,
        'evidence_basis': 'empirical',
        'comparable_country': None,
        'collected_by': 'Devin',
        'collection_date': datetime.now().strftime('%Y-%m-%d'),
        'original_text': None,
        'notes': 'Telebirr introduced millions to digital payments'
    }
]

# Convert to DataFrames
new_obs_df = pd.DataFrame(new_observations)
new_events_df = pd.DataFrame(new_events)
new_impacts_df = pd.DataFrame(new_impact_links)

# Append to existing data
enriched_data_df = pd.concat([data_df, new_obs_df, new_events_df], ignore_index=True)
enriched_impacts_df = pd.concat([impact_links_df, new_impacts_df], ignore_index=True)

print(f"\nOriginal data records: {len(data_df)}")
print(f"Added observations: {len(new_observations)}")
print(f"Added events: {len(new_events)}")
print(f"Total enriched data records: {len(enriched_data_df)}")

print(f"\nOriginal impact links: {len(impact_links_df)}")
print(f"Added impact links: {len(new_impact_links)}")
print(f"Total enriched impact links: {len(enriched_impacts_df)}")

# Save enriched data
output_path = r'C:\Users\hp\Desktop\week 11\data\processed\ethiopia_fi_unified_data_enriched.xlsx'
with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
    enriched_data_df.to_excel(writer, sheet_name='ethiopia_fi_unified_data', index=False)
    enriched_impacts_df.to_excel(writer, sheet_name='Impact_sheet', index=False)

print(f"\nEnriched data saved to: {output_path}")

# Also save as CSV for easier processing
enriched_data_df.to_csv(r'C:\Users\hp\Desktop\week 11\data\processed\ethiopia_fi_unified_data_enriched.csv', index=False)
enriched_impacts_df.to_csv(r'C:\Users\hp\Desktop\week 11\data\processed\impact_links_enriched.csv', index=False)

print("CSV files also saved to data/processed/")
